/**
 * @license MIT
 * @author h3y6e
 */

import type { ArgSchema, Command, CommandContext, LazyCommand } from "gunshi/plugin";
import { getCommandSubCommands, kebabnize, resolveLazyCommand } from "gunshi/utils";

type AnyCommand = Command | LazyCommand;

type EnvName = ((key: string) => string) | undefined;

type Globals = Iterable<[string, ArgSchema]>;

const ENV_PLUGIN = "h3y6e:env";

const HEADER = "// @generated by @h3y6e/gunshi-plugin-usage from gunshi metadata";

function flagName(key: string, arg: ArgSchema | undefined, toKebab: boolean | undefined) {
  return toKebab || arg?.toKebab ? kebabnize(key) : key;
}

function conflictsOf(arg: ArgSchema): string[] {
  return arg.conflicts === undefined ? [] : [arg.conflicts].flat();
}

function isRequired(arg: ArgSchema): boolean {
  return arg.required ?? (arg.type === "positional" && !arg.multiple && arg.default == null);
}

function q(value: string): string {
  return `"${value
    .toWellFormed()
    .replace(/[\\"\p{C}\p{Zl}\p{Zp}]/gu, (c) =>
      c === "\\" || c === '"' ? `\\${c}` : `\\u{${c.codePointAt(0)?.toString(16)}}`,
    )}"`;
}

function attrs(...items: (string | false | undefined)[]): string {
  return items
    .filter(Boolean)
    .map((item) => ` ${item}`)
    .join("");
}

function defaultAttr(value: string | boolean | number | undefined): string | undefined {
  if (value === undefined) return undefined;
  return typeof value === "boolean" ? `default=#${value}` : `default=${q(String(value))}`;
}

function commonAttrs(arg: ArgSchema): (string | false | undefined)[] {
  return [
    arg.description && `help=${q(arg.description)}`,
    !isRequired(arg) && defaultAttr(arg.default),
    arg.hidden && "hide=#true",
  ];
}

function node(head: string, ...children: (string | false | undefined)[]): string {
  const set = children.filter(Boolean);
  return set.length === 0 ? head : `${head} { ${set.join("; ")} }`;
}

function conflictsKdl(arg: ArgSchema, conflictName: (key: string) => string): string | undefined {
  const conflicts = conflictsOf(arg);
  if (conflicts.length === 0) return undefined;
  return `conflicts ${conflicts.map((c) => q(conflictName(c))).join(" ")}`;
}

function flagKdl(
  name: string,
  arg: ArgSchema,
  conflictName: (key: string) => string,
  { env, action }: { env?: string; action?: string } = {},
): string {
  const value = arg.type === "boolean" ? "" : ` <${name}>`;
  const spelling = `${arg.short ? `-${arg.short} ` : ""}--${name}${value}`;
  const head = `flag ${q(spelling)}${attrs(
    ...commonAttrs(arg),
    env && !isRequired(arg) && `env=${q(env)}`,
    isRequired(arg) && "required=#true",
    arg.type === "boolean" && !action && "bool_value=#true",
    arg.type === "boolean" && arg.negatable && `negate=${q(`--no-${name}`)}`,
    arg.multiple && "var=#true",
    action && `action=${q(action)} builtin=#true`,
  )}`;
  return node(
    head,
    arg.type === "enum" && arg.choices && `choices ${arg.choices.map((c) => q(c)).join(" ")}`,
    conflictsKdl(arg, conflictName),
  );
}

function positionalKdl(
  name: string,
  arg: ArgSchema,
  conflictName: (key: string) => string,
): string {
  const value = isRequired(arg) ? `<${name}>` : `[${name}]`;
  const head = `arg ${q(`${value}${arg.multiple ? "..." : ""}`)}${attrs(...commonAttrs(arg))}`;
  return node(head, conflictsKdl(arg, conflictName));
}

function spellingOf(command: Command, globals: Globals): (key: string) => string {
  const schemas: Record<string, ArgSchema> = { ...Object.fromEntries(globals), ...command.args };
  return (key) => {
    const name = flagName(key, schemas[key], command.toKebab);
    return schemas[key]?.type === "positional" ? name : `--${name}`;
  };
}

function globalKdl(command: Command, globals: Globals, envName: EnvName): string[] {
  const args: Record<string, ArgSchema> = command.args ?? {};
  const conflictName = spellingOf(command, globals);
  const shorts = new Set(Object.values(args).map((arg) => arg.short));
  return [...globals].flatMap(([key, arg]) => {
    if (key in args) return [];
    const action = key === "help" || key === "version" ? key : undefined;
    const short = arg.short && !shorts.has(arg.short) ? arg.short : undefined;
    const name = flagName(key, arg, command.toKebab);
    return [
      flagKdl(name, { ...arg, short }, conflictName, {
        action,
        env: action ? undefined : envName?.(key),
      }),
    ];
  });
}

function bodyKdl(
  command: Command,
  {
    positionals,
    subCommands,
    globals,
    envName,
  }: { positionals: boolean; subCommands: boolean; globals: Globals; envName: EnvName },
): string[] {
  const args: Record<string, ArgSchema> = command.args ?? {};
  const body = globalKdl(command, globals, envName);
  const conflictName = spellingOf(command, globals);
  for (const [key, arg] of Object.entries(args)) {
    if (arg.type === "positional" && !positionals) continue;
    const name = flagName(key, arg, command.toKebab);
    body.push(
      arg.type === "positional"
        ? positionalKdl(name, arg, conflictName)
        : flagKdl(name, arg, conflictName, { env: envName?.(key) }),
    );
  }
  const ordered = Object.values(args).filter((arg) => arg.type === "positional");
  const variadic = ordered.some((arg) => arg.multiple);
  const skippable = ordered.findIndex((arg) => !isRequired(arg) && !arg.multiple);
  if (positionals && skippable !== -1 && ordered.slice(skippable).some(isRequired)) {
    body.push("allow_missing_positional #true");
  }
  if (positionals && !variadic) body.push('arg "[_]..." hide=#true');
  body.push('arg "[__]..." hide=#true double_dash="required"');
  if (subCommands) body.push("subcommand_negates_reqs #true");
  if (typeof command.examples === "string") body.push(`example ${q(command.examples)}`);
  return body;
}

async function commandKdl(
  name: string,
  lazy: AnyCommand,
  depth: number,
  globals: Globals,
  envName: EnvName,
): Promise<string> {
  const command = await resolveLazyCommand(lazy, name, true);
  const indent = "  ".repeat(depth - 1);
  const head = `cmd ${q(name)}${attrs(
    command.description && `help=${q(command.description)}`,
    command.internal && "hide=#true",
  )}`;
  const subCommands = getCommandSubCommands(command);
  const lines = bodyKdl(command, {
    positionals: !subCommands,
    subCommands: !!subCommands,
    globals,
    envName,
  }).map((line) => `${indent}  ${line}`);
  const children = await Promise.all(
    [...(subCommands ?? [])].map(([n, c]) => commandKdl(n, c, depth + 1, globals, envName)),
  );
  return `${indent}${head} {\n${[...lines, ...children].join("\n")}\n${indent}}`;
}

export async function specOf(ctx: Readonly<CommandContext>, command: Command): Promise<string> {
  // gunshi sets `fallbackToEntry` on the environment, though its type omits it.
  const env: typeof ctx.env & { fallbackToEntry?: boolean } = ctx.env;
  if (!env.name) throw new Error("A usage spec needs the CLI's name; give cli() a name");
  const extensions: Record<string, { name?: EnvName } | undefined> = ctx.extensions;
  const envName = extensions[ENV_PLUGIN]?.name;
  const lines = [
    `name ${q(env.name)}`,
    `bin ${q(env.name)}`,
    ...(env.version ? [`version ${q(env.version)}`] : []),
    ...(env.description ? [`about ${q(env.description)}`] : []),
    "disable_help #true",
    "disable_version_flag #true",
    ...(env.strict ? ['unknown_flags "error"'] : []),
  ];
  const globals = [...(env.globalOptions ?? [])];
  const subCommands = [...(env.subCommands ?? [])].filter(([, sub]) => sub !== env.entryCommand);
  lines.push(
    ...bodyKdl(command, {
      positionals: env.fallbackToEntry || subCommands.length === 0,
      subCommands: subCommands.length > 0,
      globals,
      envName,
    }),
  );
  lines.push(
    ...(await Promise.all(
      subCommands.map(([name, sub]) => commandKdl(name, sub, 1, globals, envName)),
    )),
  );
  return [HEADER, ...lines].join("\n");
}
