import { spawnSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { cli, define, lazy } from "gunshi";
import { plugin } from "gunshi/plugin";
import { afterAll, afterEach, beforeAll, describe, expect, test, vi } from "vitest";

import usage from "./index.ts";

type Options = NonNullable<Parameters<typeof cli>[2]>;

async function generate(entry: Parameters<typeof cli>[1], options: Options): Promise<string> {
  const log = vi.spyOn(console, "log").mockImplementation(() => {});
  await cli(["usage"], entry, { ...options, plugins: [...(options.plugins ?? []), usage()] });
  const spec = log.mock.calls.map((call) => call.join(" ")).join("\n");
  log.mockRestore();
  return spec;
}

const sync = define({
  name: "sync",
  description: "Sync a project",
  toKebab: true,
  examples: "app sync web --dry-run",
  args: {
    project: { type: "positional", description: "Project name" },
    dryRun: { type: "boolean", description: "Show the plan only" },
    jobs: { type: "number", description: "Parallel jobs" },
    mode: { type: "enum", choices: ["fast", "safe"], description: "Sync mode" },
    tag: { type: "string", multiple: true, description: "Tags to sync" },
    color: { type: "boolean", negatable: true, default: true, description: "Colorize output" },
    out: {
      type: "string",
      metavar: "FILE",
      conflicts: ["stdout", "dryRun"],
      description: "Output file",
    },
    stdout: { type: "boolean", description: "Write to stdout" },
    trace: { type: "boolean", hidden: true },
  },
  run: (c) => console.log(`jobs=${c.values.jobs}`),
});

const status = define({
  name: "status",
  description: "Show status",
  args: {
    json: { type: "boolean", description: "Print JSON" },
    host: { type: "string", description: "Host to query" },
  },
  run: (c) => console.log(`host=${c.values.host}`),
});

const entry = define({ name: "app", run: () => {} });

const options = {
  name: "app",
  version: "1.2.3",
  description: "Sample app",
  subCommands: {
    status,
    sync,
    remote: lazy(async () => define({ name: "remote", run: () => {} }), {
      name: "remote",
      description: "Manage remotes",
    }),
    debug: define({ name: "debug", internal: true, run: () => {} }),
  },
  strict: true,
  renderHeader: null,
};

async function runApp(argv: string[]): Promise<string> {
  const log = vi.spyOn(console, "log").mockImplementation(() => {});
  await cli(argv, entry, options);
  return log.mock.calls.map((call) => call.join(" ")).join("\n");
}

function lint(kdl: string) {
  const dir = mkdtempSync(join(tmpdir(), "gunshi-plugin-usage-lint-"));
  try {
    writeFileSync(join(dir, "lint.usage.kdl"), kdl);
    return spawnSync("usage", ["lint", join(dir, "lint.usage.kdl")], { encoding: "utf8" });
  } finally {
    rmSync(dir, { recursive: true });
  }
}

async function writeSpec(
  entry: Parameters<typeof generate>[0],
  options: Options,
  path: string,
): Promise<void> {
  writeFileSync(path, `${await generate(entry, options)}\n`);
}

let dir: string;

beforeAll(() => {
  dir = mkdtempSync(join(tmpdir(), "gunshi-plugin-usage-"));
});

afterAll(() => {
  rmSync(dir, { recursive: true });
});

afterEach(() => {
  vi.restoreAllMocks();
  vi.unstubAllEnvs();
});

describe("spec", () => {
  test("when a CLI has subcommands, generate returns a KDL spec that usage lint accepts", async () => {
    // Arrange
    const app = { entry, options };

    // Act
    const kdl = await generate(app.entry, app.options);

    // Assert
    expect(kdl).toMatchInlineSnapshot(`
      "// @generated by @h3y6e/gunshi-plugin-usage from gunshi metadata
      name "app"
      bin "app"
      version "1.2.3"
      about "Sample app"
      disable_help #true
      disable_version_flag #true
      unknown_flags "error"
      flag "-h --help" help="Display this help message" action="help" builtin=#true
      flag "-v --version" help="Display this version" action="version" builtin=#true
      arg "[__]..." hide=#true double_dash="required"
      subcommand_negates_reqs #true
      cmd "status" help="Show status" {
        flag "-h --help" help="Display this help message" action="help" builtin=#true
        flag "-v --version" help="Display this version" action="version" builtin=#true
        flag "--json" help="Print JSON" bool_value=#true
        flag "--host <host>" help="Host to query"
        arg "[_]..." hide=#true
        arg "[__]..." hide=#true double_dash="required"
      }
      cmd "sync" help="Sync a project" {
        flag "-h --help" help="Display this help message" action="help" builtin=#true
        flag "-v --version" help="Display this version" action="version" builtin=#true
        arg "<project>" help="Project name"
        flag "--dry-run" help="Show the plan only" bool_value=#true
        flag "--jobs <jobs>" help="Parallel jobs"
        flag "--mode <mode>" help="Sync mode" { choices "fast" "safe" }
        flag "--tag <tag>" help="Tags to sync" var=#true
        flag "--color" help="Colorize output" default=#true bool_value=#true negate="--no-color"
        flag "--out <out>" help="Output file" { conflicts "--stdout" "--dry-run" }
        flag "--stdout" help="Write to stdout" bool_value=#true
        flag "--trace" hide=#true bool_value=#true
        arg "[_]..." hide=#true
        arg "[__]..." hide=#true double_dash="required"
        example "app sync web --dry-run"
      }
      cmd "remote" help="Manage remotes" {
        flag "-h --help" help="Display this help message" action="help" builtin=#true
        flag "-v --version" help="Display this version" action="version" builtin=#true
        arg "[_]..." hide=#true
        arg "[__]..." hide=#true double_dash="required"
      }
      cmd "debug" hide=#true {
        flag "-h --help" help="Display this help message" action="help" builtin=#true
        flag "-v --version" help="Display this version" action="version" builtin=#true
        arg "[_]..." hide=#true
        arg "[__]..." hide=#true double_dash="required"
      }
      cmd "usage" help="Print the usage spec" hide=#true {
        flag "-h --help" help="Display this help message" action="help" builtin=#true
        flag "-v --version" help="Display this version" action="version" builtin=#true
        arg "[_]..." hide=#true
        arg "[__]..." hide=#true double_dash="required"
      }"
    `);
    const result = lint(kdl);
    expect(result.status, `${result.stdout}${result.stderr}`).toBe(0);
  });

  test("when a lazy command declares args and internal on lazy() and loads a runner, the spec includes them", async () => {
    // Arrange
    const lz = lazy(async () => () => {}, {
      name: "lz",
      description: "Lazy",
      args: { host: { type: "string" } },
      internal: true,
    });

    // Act
    const kdl = await generate(entry, { name: "app", subCommands: { lz } });

    // Assert
    expect(kdl).toMatch(/^cmd "lz" help="Lazy" hide=#true \{$/m);
    expect(kdl).toMatch(/^ {2}flag "--host <host>"$/m);
  });

  test("when a positional is multiple or has a default, the spec marks it optional like gunshi", async () => {
    // Arrange
    const app = define({
      name: "app",
      args: {
        target: { type: "positional", default: "web" },
        files: { type: "positional", multiple: true },
      },
      run: () => {},
    });

    // Act
    const kdl = await generate(app, { name: "app" });

    // Assert
    expect(kdl).toContain('arg "[target]" default="web"');
    expect(kdl).toContain('arg "[files]..."');
  });

  test("when a command has toKebab, the spec names its positionals in kebab case like gunshi", async () => {
    // Arrange
    const app = define({
      name: "app",
      toKebab: true,
      args: { outDir: { type: "positional" } },
      run: () => {},
    });

    // Act
    const kdl = await generate(app, { name: "app" });

    // Assert
    expect(kdl).toContain('arg "<out-dir>"');
  });

  test("when the entry command is named apart from the CLI, the spec includes a sub-command named like the CLI and omits the entry", async () => {
    // Arrange
    const root = define({ name: "root", run: () => {} });
    const app = define({ name: "app", run: () => {} });

    // Act
    const kdl = await generate(root, { name: "app", subCommands: { app } });

    // Assert
    expect(kdl).toContain('cmd "app"');
    expect(kdl).not.toContain('cmd "root"');
  });

  test("when the env plugin is in plugins, the spec names the variable of each flag it can fill", async () => {
    // Arrange
    const app = define({
      name: "app",
      args: {
        loud: { type: "boolean" },
        token: { type: "string", required: true },
        target: { type: "positional", required: false },
      },
      run: () => {},
    });
    const env = plugin({
      id: "h3y6e:env",
      extension: () => ({ name: (key: string) => `APP_${key.toUpperCase()}` }),
    });

    // Act
    const kdl = await generate(app, { name: "app", plugins: [env] });

    // Assert
    expect(kdl).toContain('flag "--loud" env="APP_LOUD" bool_value=#true');
    expect(kdl).toContain('flag "--token <token>" required=#true');
    expect(kdl).toContain('arg "[target]"\n');
    expect(kdl).toContain('flag "-h --help" help="Display this help message" action="help"');
  });

  test("when only a plugin adds a command, gunshi falls back to the entry and the spec keeps the entry's positionals", async () => {
    // Arrange
    const app = define({ name: "app", args: { name: { type: "positional" } }, run: () => {} });
    const adder = plugin({
      id: "x:adder",
      setup: (ctx) => ctx.addCommand("extra", { name: "extra", run: () => {} }),
    });

    // Act
    const kdl = await generate(app, { name: "app", plugins: [adder] });

    // Assert
    expect(kdl).toMatch(/^arg "<name>"$/m);
  });

  test("when a plugin adds a global option with toKebab, the spec spells it in kebab case", async () => {
    // Arrange
    const kebab = plugin({
      id: "x:kebab",
      setup: (ctx) => ctx.addGlobalOption("dryRun", { type: "boolean", toKebab: true }),
    });

    // Act
    const kdl = await generate(entry, { name: "app", plugins: [kebab] });

    // Assert
    expect(kdl).toContain('flag "--dry-run" bool_value=#true');
  });

  test("when another plugin adds a global option and a command, the spec includes both", async () => {
    // Arrange
    const other = plugin({
      id: "x:other",
      setup: (ctx) => {
        ctx.addGlobalOption("dry-run", { type: "boolean", description: "Dry run" });
        ctx.addCommand("extra", { name: "extra", description: "From a plugin", run: () => {} });
      },
    });

    // Act
    const kdl = await generate(entry, { name: "app", plugins: [other] });

    // Assert
    expect(kdl).toContain('flag "--dry-run" help="Dry run" bool_value=#true');
    expect(kdl).toContain('cmd "extra" help="From a plugin"');
  });
});

describe("top level and nesting", () => {
  test("when the entry command declares examples and a command nests another, the spec carries each at its level", async () => {
    // Arrange
    const app = define({
      name: "app",
      examples: "app web",
      run: () => {},
    });
    const inner = define({ name: "inner", run: () => {} });
    const outer = define({ name: "outer", subCommands: { inner }, run: () => {} });

    // Act
    const kdl = await generate(app, {
      name: "app",
      subCommands: { outer },
    });

    // Assert
    expect(kdl).toContain('example "app web"');
    expect(kdl).toMatch(/^subcommand_negates_reqs #true$/m);
    expect(kdl).toContain(
      [
        'cmd "outer" {',
        '  flag "-h --help" help="Display this help message" action="help" builtin=#true',
        '  flag "-v --version" help="Display this version" action="version" builtin=#true',
        '  arg "[__]..." hide=#true double_dash="required"',
        "  subcommand_negates_reqs #true",
        '  cmd "inner" {',
        '    flag "-h --help" help="Display this help message" action="help" builtin=#true',
        '    flag "-v --version" help="Display this version" action="version" builtin=#true',
        '    arg "[_]..." hide=#true',
        '    arg "[__]..." hide=#true double_dash="required"',
        "  }",
        "}",
      ].join("\n"),
    );
    const result = lint(kdl);
    expect(result.status, `${result.stdout}${result.stderr}`).toBe(0);
  });
});

describe("KDL strings", () => {
  test("when a description has quotes, backslashes, control characters, and non-ASCII text, usage lint accepts the spec and reads the text back", async () => {
    // Arrange
    const text = 'say "hi" \\ tab\t bell\u0007 literal \\u0041 \u0085 \u2028 \u200e \ufeff 日本語';

    // Act
    await writeSpec(
      define({ name: "app", run: () => {} }),
      {
        name: "app",
        description: text,
      },
      join(dir, "app.usage.kdl"),
    );

    // Assert
    const lint = spawnSync("usage", ["lint", join(dir, "app.usage.kdl")], { encoding: "utf8" });
    expect(lint.status, lint.stdout + lint.stderr).toBe(0);
    const json = spawnSync("usage", ["generate", "json", "-f", join(dir, "app.usage.kdl")], {
      encoding: "utf8",
    });
    expect(JSON.parse(json.stdout).about).toBe(text);
  });
});

describe("spec fidelity", () => {
  beforeAll(async () => {
    await writeSpec(entry, options, join(dir, "app.usage.kdl"));
  });

  test.each([
    { argv: ["sync", "web", "--dry-run"], accepted: true },
    { argv: ["sync", "web", "--no-color", "--tag", "a", "--tag", "b"], accepted: true },
    { argv: ["sync", "web", "--mode", "turbo"], accepted: false },
    { argv: ["sync", "web", "--out", "x", "--stdout"], accepted: false },
    { argv: ["sync", "web", "--out", "x", "--dry-run"], accepted: false },
    { argv: ["sync", "web", "--bogus"], accepted: false },
    { argv: ["sync"], accepted: false },
    { argv: ["-v"], accepted: true },
    { argv: ["-V"], accepted: false },
    { argv: ["help"], accepted: false },
    { argv: ["sync", "-h"], accepted: true },
  ])(
    "when gunshi parses $argv, usage explain reaches the same verdict",
    async ({ argv, accepted }) => {
      // Arrange
      const spec = join(dir, "app.usage.kdl");

      // Act
      const explain = spawnSync(
        "usage",
        ["explain", "-f", spec, "--format", "json", "--", "app", ...argv],
        { encoding: "utf8" },
      );
      const report = JSON.parse(explain.stdout);
      const gunshi = await runApp(argv).then(
        () => true,
        () => false,
      );

      // Assert
      expect(report.errors.length === 0 && report.refused === null).toBe(accepted);
      expect(gunshi).toBe(accepted);
    },
  );
});

describe("gunshi semantics", () => {
  async function verdicts(entry: Parameters<typeof cli>[1], options: Options, argv: string[]) {
    const spec = join(dir, "semantics.usage.kdl");
    const kdl = await generate(entry, options);
    writeFileSync(spec, kdl);
    const explain = spawnSync(
      "usage",
      ["explain", "-f", spec, "--format", "json", "--", String(options.name), ...argv],
      { encoding: "utf8" },
    );
    const report = JSON.parse(explain.stdout);
    vi.spyOn(console, "log").mockImplementation(() => {});
    const gunshi = await cli(argv, entry, {
      ...options,
      renderHeader: null,
      renderValidationErrors: null,
      plugins: [...(options.plugins ?? []), usage()],
    }).then(
      () => true,
      () => false,
    );
    return {
      usage: report.errors.length === 0 && report.refused === null,
      gunshi,
      lint: lint(kdl).status,
    };
  }

  const run = () => {};
  const sub = define({ name: "sub", run });
  const kebab = plugin({
    id: "x:kebab",
    setup: (ctx) => ctx.addGlobalOption("dryRun", { type: "boolean" }),
  });

  test.each([
    {
      case: "fallbackToEntry is true beside sub-commands",
      entry: define({ name: "app", args: { name: { type: "positional" } }, run }),
      options: { name: "app", subCommands: { sub }, fallbackToEntry: true },
      argv: ["world"],
      accepted: true,
    },
    {
      case: "a required arg has a default",
      entry: define({
        name: "app",
        args: { s: { type: "string", required: true, default: "a" } },
        run,
      }),
      options: { name: "app" },
      argv: [],
      accepted: false,
    },
    {
      case: "an optional positional precedes a required one",
      entry: define({
        name: "app",
        args: { src: { type: "positional", required: false }, dest: { type: "positional" } },
        run,
      }),
      options: { name: "app" },
      argv: ["only"],
      accepted: true,
    },
    {
      case: "a flag conflicts with a given positional",
      entry: define({
        name: "app",
        args: {
          from: { type: "string", conflicts: "target" },
          target: { type: "positional", required: false },
        },
        run,
      }),
      options: { name: "app" },
      argv: ["--from", "a", "x"],
      accepted: false,
    },
    {
      case: "two positionals share a metavar",
      entry: define({
        name: "app",
        args: {
          src: { type: "positional", metavar: "string" },
          dest: { type: "positional", metavar: "string" },
        },
        run,
      }),
      options: { name: "app" },
      argv: ["a"],
      accepted: false,
    },
    {
      case: "a command flag takes the short letter of a global",
      entry: define({ name: "app", args: { verbose: { type: "boolean", short: "v" } }, run }),
      options: { name: "app", version: "1.0.0" },
      argv: ["-v"],
      accepted: true,
    },
    {
      case: "a toKebab command has a plugin's global option",
      entry: define({ name: "app", run }),
      options: {
        name: "app",
        subCommands: { sub: define({ name: "sub", toKebab: true, run }) },
        plugins: [kebab],
      },
      argv: ["sub", "--dry-run"],
      accepted: true,
    },
    {
      case: "a global option conflicts with a toKebab command flag",
      entry: define({ name: "app", toKebab: true, args: { forceAll: { type: "boolean" } }, run }),
      options: {
        name: "app",
        plugins: [
          plugin({
            id: "x:global-conflict",
            setup: (ctx) =>
              ctx.addGlobalOption("quiet", { type: "boolean", conflicts: "forceAll" }),
          }),
        ],
      },
      argv: ["--quiet", "--force-all"],
      accepted: false,
    },
    {
      case: "a command flag conflicts with a toKebab global option",
      entry: define({
        name: "app",
        args: { force: { type: "boolean", conflicts: "dryRun" } },
        run,
      }),
      options: {
        name: "app",
        plugins: [
          plugin({
            id: "x:kebab-global",
            setup: (ctx) => ctx.addGlobalOption("dryRun", { type: "boolean", toKebab: true }),
          }),
        ],
      },
      argv: ["--force", "--dry-run"],
      accepted: false,
    },
  ])(
    "when $case, gunshi and usage explain agree on $argv and usage lint accepts the spec",
    async ({ entry, options, argv, accepted }) => {
      // Arrange
      const expected = { usage: accepted, gunshi: accepted, lint: 0 };

      // Act
      const actual = await verdicts(entry, options as Options, argv);

      // Assert
      expect(actual).toEqual(expected);
    },
  );

  test("when a sub-command declares its own version arg, the spec gives that command the arg instead of the builtin", async () => {
    // Arrange
    const install = define({ name: "install", args: { version: { type: "string" } }, run });

    // Act
    const kdl = await generate(define({ name: "app", run }), {
      name: "app",
      version: "1.0.0",
      subCommands: { install },
    });

    // Assert
    const block = kdl.slice(kdl.indexOf('cmd "install"'));
    expect(block).toContain('flag "--version <version>"');
    expect(block.slice(0, block.indexOf("}"))).not.toContain('action="version"');
  });

  test("when a command gives examples as a function, the spec leaves them out", async () => {
    // Arrange
    const app = define({ name: "app", examples: async () => "app --dynamic", run });

    // Act
    const kdl = await generate(app, { name: "app" });

    // Assert
    expect(kdl).not.toContain("example");
  });

  test("when usageSilent is set, the usage command still prints the spec", async () => {
    // Arrange
    const options = { name: "app", usageSilent: true };

    // Act
    const kdl = await generate(define({ name: "app", run }), options);

    // Assert
    expect(kdl).toMatch(/^name "app"$/m);
  });

  test("when a description has a lone surrogate, usage lint accepts the spec", async () => {
    // Arrange
    const app = define({ name: "app", description: "broken \uD83D tail", run });

    // Act
    const kdl = await generate(app, { name: "app" });

    // Assert
    expect(lint(kdl).status).toBe(0);
  });
});
